name: Generate Graphs

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install packages
        run: |
          install.packages(c(
            "tidyverse",
            "ggplot2",
            "eurostat",
            "dplyr",
            "showtext",
            "tidyr",
            "scales"
          ))
      - name: Run script
        run: Rscript Greekonomics_51_public.R
      - name: Upload plots
        uses: actions/upload-artifact@v4
        with:
          name: graphs
          path: plots/
